apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-volume
  labels:
    type: nfs
    name: wordpress-nfs-vol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/IT-Academy/nfs-data/sa2-19-22/Sergei_Svinobaev/wordpress
    server: 192.168.37.105
