name: Docker image CI

on:
  release:
    types: [published]
  push:
    branches:
      - "main"
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GIT_TOKEN }} 

  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [tag]      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login in DockerHub registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker_image:${{needs.tag.outputs.new_tag}}
