on: [push, pull_request]
name: Validate
jobs:
  kubeval:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifests: [prometheus.yaml, grafana.yaml]      
    steps:
    - uses: actions/checkout@master
    - name: test manifests folder
      uses: instrumenta/kubeval-action@master
      with: 
       files: ${{matrix.manifests}}
